### ISSUE TITLE
Error: Cannot find module '@oclif/errors'

### ISSUE THREAD

**Issue by elliottsj** [apollographql/apollo-tooling#1067]
When using a strict package manager such as pnpm (or yarn pnp), running `apollo` will fail with error `Error: Cannot find module '@oclif/errors'`. This is because node cannot [resolve the `@oclif/errors` import](https://github.com/apollographql/apollo-tooling/blob/80a715dc2396b79278c8006e024b5393af83175d/packages/apollo/bin/run#L4) due to pnpm's strict `node_modules` structure, since `@oclif/errors` is not declared in package.json "dependencies".

**Intended outcome:**

No fatal error when launching the Apollo CLI.

**Actual outcome:**

```
> apollo client:codegen --config=./apollo.config.js --target=typescript --outputFlat ./graphql-types.ts --watch

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@oclif/errors'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/spencerelliott/Dev/Yolk-HQ/yolkjs/common/temp/node_modules/.registry.npmjs.org/@oclif/config/1.12.0/node_modules/@oclif/config/lib/config.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**How to reproduce the issue:**

```shell
npm install --global pnpm
pnpm install apollo
./node_modules/.bin/apollo
```

**Versions**

```shell
$ npm -v
6.8.0
$ pnpm -v
2.25.6
$ node -v
v10.15.0
```

**Comment by ngryman** [comment]
I've got the same error with the following versions:

* `yarn@2.0.0-rc.28`
* `apollo@2.22.0`

Here is the error:
```sh
$ yarn apollo codegen:generate [...]
/usr/src/[...]/.pnp.js:18966
    throw firstError;
    ^

Error: A package is trying to access another package without the second one bei
ng listed as a dependency of the first one

Required package: @oclif/errors (via "@oclif/errors")
Required by: @oclif/config@npm:1.13.3 (via /usr/src/[...]/.yarn/cache/@oclif-co
nfig-npm-1.13.3-34782a5d37-1.zip/node_modules/@oclif/config/lib/)

Require stack:
- /usr/src/[...]/.yarn/cache/@oclif-config-npm-1.13.3-34782a5d37-1.zip/node_mod
ules/@oclif/config/lib/config.js
- /usr/src/[...]/.yarn/cache/@oclif-config-npm-1.13.3-34782a5d37-1.zip/node_mod
ules/@oclif/config/lib/index.js
- /usr/src/[...]/.yarn/$$virtual/@oclif-command-virtual-61f5a1f0c7/0/cache/@ocl
if-command-npm-1.5.19-b10e786c92-1.zip/node_modules/@oclif/command/lib/command.
js
- /usr/src/[...]/.yarn/$$virtual/@oclif-command-virtual-61f5a1f0c7/0/cache/@ocl
if-command-npm-1.5.19-b10e786c92-1.zip/node_modules/@oclif/command/lib/index.js
- /usr/src/[...]/.yarn/cache/apollo-npm-2.22.0-00d6f3d687-1.zip/node_modules/ap
ollo/bin/run
    at Object.makeError (/usr/src/[...]/.pnp.js:10711:24)
    at resolveToUnqualified (/usr/src/[...]/.pnp.js:19574:35)
    at resolveRequest (/usr/src/[...]/.pnp.js:19651:27)
    at Object.resolveRequest (/usr/src/[...]/.pnp.js:19719:26)
    at Function.module_1.Module._resolveFilename (/usr/src/[...]/.pnp.js:18949:
34)
    at Function.module_1.Module._load (/usr/src/[...]/.pnp.js:18834:40)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/src/[...]/.yarn/cache/@oclif-config-npm-1.13.3-
34782a5d37-1.zip/node_modules/@oclif/config/lib/config.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND',
  pnpCode: 'UNDECLARED_DEPENDENCY',
  data: {
    request: '@oclif/errors',
    issuer: '/usr/src/[...]/.yarn/cache/@oclif-config-npm-1.13.3-34782a5d37-1.z
ip/node_modules/@oclif/config/lib/',
    issuerLocator: { name: '@oclif/config', reference: 'npm:1.13.3' },
    dependencyName: '@oclif/errors',
    candidates: [ '@oclif/config', '@oclif/parser', 'debug', 'tslib' ]
  },
  requireStack: [
    '/usr/src/[...]/.yarn/cache/@oclif-config-npm-1.13.3-34782a5d37-1.zip/node_
modules/@oclif/config/lib/config.js',
    '/usr/src/[...]/.yarn/cache/@oclif-config-npm-1.13.3-34782a5d37-1.zip/node_
modules/@oclif/config/lib/index.js',
    '/usr/src/[...]/.yarn/$$virtual/@oclif-command-virtual-61f5a1f0c7/0/cache/@
oclif-command-npm-1.5.19-b10e786c92-1.zip/node_modules/@oclif/command/lib/comma
nd.js',
    '/usr/src/[...]/.yarn/$$virtual/@oclif-command-virtual-61f5a1f0c7/0/cache/@
oclif-command-npm-1.5.19-b10e786c92-1.zip/node_modules/@oclif/command/lib/index
.js',
    '/usr/src/[...]/.yarn/cache/apollo-npm-2.22.0-00d6f3d687-1.zip/node_modules
/apollo/bin/run'
  ]
}
```
