### ISSUE TITLE
multiple schema not working as expected

### ISSUE THREAD

**Issue by veeramarni** [apollographql/apollo-tooling#1211]
**Intended outcome:**

Should work as mentioned in https://github.com/apollographql/apollo-tooling/issues/841#issuecomment-462927121

**Actual outcome:**

```
$ ./node_modules/.bin/apollo client:codegen --target typescript --outputFlat out
.../sandbox-apollo-client/client-package/src/client-query.gql: Cannot query field "isOriginExist" on type "Query".
{ ToolError: Validation of GraphQL query document failed
    at Object.validateQueryDocument (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo-language-server/lib/errors/validation.js:32:19)
    at Object.generate [as default] (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo/lib/generate.js:22:18)
    at write (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at Task.task (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo/lib/commands/client/codegen.js:86:46) name: 'ToolError' }
  ✔ Loading Apollo Project
  ✖ Generating query files with 'typescript' target
    → Validation of GraphQL query document failed
.../sandbox-apollo-client/client-package/src/client-query.gql: Cannot query field "isOriginExist" on type "Query".
{ ToolError: Validation of GraphQL query document failed
    at Object.validateQueryDocument (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo-language-server/lib/errors/validation.js:32:19)
    at Object.generate [as default] (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo/lib/generate.js:22:18)
    at write (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo/lib/commands/client/codegen.js:67:54)
    at GraphQLClientProject.project.onDiagnostics [as _onDiagnostics] (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo/lib/commands/client/codegen.js:84:29)
    at GraphQLClientProject.validate (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo-language-server/lib/project/client.js:123:18)
    at GraphQLClientProject.validateIfNeeded (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo-language-server/lib/project/base.js:135:14)
    at Timeout.setTimeout [as _onTimeout] (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo-language-server/lib/project/base.js:127:22)
```

**How to reproduce the issue:**
Add additional client schema https://github.com/veeramarni/sandbox-apollo-client/blob/master/client-package/src/clientSchema.graphqls

And run 

`apollo client:codegen --target typescript --outputFlat out`

**Versions**
^2.9.0

**Comment by veeramarni** [comment]
It seems it could not reconize `*.graphqls` even it was included in the `includes`. So after changing a file to `.graphql` i have this error. 

```
$ ./node_modules/.bin/apollo client:codegen --target typescript --outputFlat out
{ Error: Error in "Loading schema for my-project": Cannot extend type "Origin" because it does not exist in the existing schema.

file:///Users/workspace/phoneapps/development/examples/sandbox-apollo-client/client-package/src/clientSchema.graphql (3:1)
2: 
3: extend type Origin {
   ^
4:     isExist: Boolean

    at Object.error (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/@oclif/errors/lib/index.js:22:17)
    at Generate.error (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/@oclif/command/lib/command.js:48:23)
    at OclifLoadingHandler.showError (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo/lib/OclifLoadingHandler.js:28:22)
    at OclifLoadingHandler.handle (/Users/workspace/phoneapps/development/examples/sandbox-apollo-client/node_modules/apollo/lib/OclifLoadingHandler.js:13:18) oclif: { exit: 2 }, code: undefined }
  ✖ Loading Apollo Project
    → 4:     isExist: Boolean
    Generating query files
 ›   Error: Error initializing Apollo GraphQL project "my-project": Error: Error in "Loading schema for my-project": Cannot extend type "Origin" because it does not exist in the existing schema.
 ›
 ›   file:///Users/workspace/phoneapps/development/examples/sandbox-apollo-client/client-package/src/clientSchema.graphql (3:1)
 ›   2: 
 ›   3: extend type Origin {
 ›       ^
 ›   4:     isExist: Boolean
 ›
```

**Comment by JakeDawkins** [comment]
@veeramarni a couple thoughts

I cloned your project and ran it, and I didn't see the same issue. I ran the exact command you pasted with version 2.9.0 of the CLI. Where are you running the command from? The root of the project?

Also, I'm not really sure what's going on here. The directory structure seems a bit weird to me, that there are two top-level source folders and both of them are supposedly the same client? Try moving things back under the `src` folder, and that may help whatever is going on here

**Comment by berrylaw** [comment]
Actually no real person teach me  the rule
That’s y don’t ask me anything , better You find your boss, I have to take
a rest now.

「Jake Dawkins <notifications@github.com>」在 2019年4月26日 週五，下午10:10 寫道：

**Comment by JakeDawkins** [comment]
I don't understand @berrylaw

**Comment by veeramarni** [comment]
@JakeDawkins 

I think I now understood the schema extension only works for client schema. 

Can we extend schemas on the server(service) side? If not then this is not an issue, may be asking for a new feature to perform server-side schema extension.

We normally have a  root schema which is just a simple template and then we have another server-side schema that would have the actual project related schema. And we start the graphql server with `[rootSchema.graphql].concat(projectSchema.graphql)`. We hope we can do something like with `apollo-tooling` to merge multi schemas and provide to `--localSchemaFile`.

Server Side
---
 - RootSchema (plain template which is common in all our projects)
   - Project Schema  (this file is not getting recognized)

Client Side
---
 - ClientSchema with additional types added with `extend`. (this works fine)

**Comment by JakeDawkins** [comment]
Closing. This should be covered by another issue #1026 :)
