### ISSUE TITLE
`apollo service:check --markdown` options throw error

### ISSUE THREAD

**Issue by vreality64** [apollographql/apollo-tooling#1243]
**Intended outcome:**

```sh
$ npx apollo service:check --tag develop --markdown
```

I think markdown output should be in form not error.

---
### Apollo Service Check
🔄 Validated your local schema against schema tag `develop` on service `...`.
🔢 Compared **0 schema change** against **0 operations** seen over the **last 30 days**.
✅ Found **no breaking changes**.

🔗 [View your service check details](#).

---

**Actual outcome:**

**Error**
```sh
$ npx apollo service:check --tag develop --markdown
Error: checkSchemaResult.diffToPrevious.validationConfig missing
    at formatMarkdown (~/.../service/check.js:54:15)
    at ServiceCheck.run (~/.../service/check.js:208:29)
    at <anonymous>
```

**How to reproduce the issue:**

_**Pre condition**_: **no changes between local and engine schema**. if schema changes, it works. It's normal case as CI integration command `service:check`

```sh
$ npx apollo service:check --markdown
```

**Versions**

```sh
$ npx apollo -v

apollo/2.9.0 darwin-x64 node-v8.11.3
```

**Comment by trevor-scheer** [comment]
@justinanastos, would you mind taking a look at this? Seems like a valid bug.

**Comment by parshap** [comment]
I'm running into this same issue as well when `apollo service:check` runs in CI, though it runs fine for me locally.
