### ISSUE TITLE
VS Code Protocol not supported error

### ISSUE THREAD

**Issue by thefinnomenon** [apollographql/apollo-tooling#1252]
**Intended outcome:**
When I try to configure the VS Code extension with my remote schema
```
module.exports = {
  client: {
    service: {
      name: 'my-app',
      url: 'http://localhost:4000/graphql',
    },
  },
};
```
I expect it to load the schema & enable the extension features.

I expect the same when I load the schema locally.
```
module.exports = {
  client: {
    service: {
      name: 'my-app',
      localSchemaFile: './schema.json',
    },
  },
};

```
**Actual outcome:**
In both cases I get the following error from the extension.
```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:109:11)
    at request (https.js:272:10)
    at /Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/node-fetch/lib/index.js:1421:15
    at new Promise (<anonymous>)
    at fetch (/Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/node-fetch/lib/index.js:1390:9)
    at /Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/apollo-link-http/lib/httpLink.js:70:13
    at new Subscription (/Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/zen-observable/lib/Observable.js:183:34)
    at Observable.subscribe (/Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/zen-observable/lib/Observable.js:262:14)
    at /Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/apollo-link/lib/linkUtils.js:43:20
    at new Promise (<anonymous>)
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:109:11)
    at request (https.js:272:10)
    at /Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/node-fetch/lib/index.js:1421:15
    at new Promise (<anonymous>)
    at fetch (/Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/node-fetch/lib/index.js:1390:9)
    at /Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/apollo-link-http/lib/httpLink.js:70:13
    at new Subscription (/Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/zen-observable/lib/Observable.js:183:34)
    at Observable.subscribe (/Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/zen-observable/lib/Observable.js:262:14)
    at /Users/finn/.vscode/extensions/apollographql.vscode-apollo-1.6.4/node_modules/apollo-link/lib/linkUtils.js:43:20
    at new Promise (<anonymous>)
```
**How to reproduce the issue:**

All I did was install the extension & add the apollo.config.js that you see above.

**Versions**

apollographql.vscode-apollo-1.6.4

**Comment by thefinnomenon** [comment]
Hmm yeah I have no idea, it is working now but not sure why. Must've been a conflicting config file or something. Thanks.
