### ISSUE TITLE
download-schema with Gatsby project

### ISSUE THREAD

**Issue by Siyfion** [apollographql/apollo-tooling#1266]
I tried using the command `apollo client:download-schema` with an `apollo.config.js` containing the following:

```
module.exports = {
  client: {
    service: {
      name: 'test-website',
      url: 'http://localhost:8000/___graphql',
    },
  },
}
``` 

With a Gatsby site running in development mode.

**Intended outcome:**

A valid `schema.json` file to be outputted.

**Actual outcome:**

The following error:

```
> apollo client:download-schema
  ✔ Loading Apollo Project
  ✖ Saving schema to schema.json
    → spurious results.
Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.
Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.
https://yarnpkg.com/en/docs/selective-version-resolutions
Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (~/.config/yarn/global/node_modules/apollo/node_modules/graphql/jsutils/instanceOf.js:37:13)
    at isSchema (~/.config/yarn/global/node_modules/apollo/node_modules/graphql/type/schema.js:34:34)
    at assertSchema (~/.config/yarn/global/node_modules/apollo/node_modules/graphql/type/schema.js:38:4)
    at validateSchema (~/.config/yarn/global/node_modules/apollo/node_modules/graphql/type/validate.js:53:28)
    at assertValidSchema (~/.config/yarn/global/node_modules/apollo/node_modules/graphql/type/validate.js:77:16)
    at assertValidExecutionArguments (~/.config/yarn/global/node_modules/apollo/node_modules/graphql/execution/execute.js:146:35)
    at executeImpl (~/.config/yarn/global/node_modules/apollo/node_modules/graphql/execution/execute.js:67:3)
    at execute (~/.config/yarn/global/node_modules/apollo/node_modules/graphql/execution/execute.js:62:256)
    at Object.introspectionFromSchema (~/.config/yarn/global/node_modules/apollo/node_modules/graphql/utilities/introspectionFromSchema.js:38:37)
    at Task.task (~/.config/yarn/global/node_modules/apollo/lib/commands/client/download-schema.js:15:78)
``` 
**How to reproduce the issue:**

1. Clone the Gatsby Starter Blog: https://github.com/gatsbyjs/gatsby-starter-blog
2. Create an `apollo.config.js` file with the above contents
3. Run `apollo client:download-schema`

**Versions**

apollo/2.11.1 darwin-x64 node-v10.13.0

**Comment by trevor-scheer** [comment]
Hey @Siyfion, thanks for submitting an issue. The single instance of `graphql` is a problem we face with this tool on a pretty regular basis, as it's a runtime dependency of the tool.

If you `npm ls graphql`, you'll probably see multiple versions in your tree and where they're coming from. If it's possible to update your dependencies in such a way that everything is on the same version of `graphql` (and graphql is completely deduped), that's one potential solution.

Another option is to remove `apollo` from the project completely and run it via npx, a la:
`npx apollo@2.11.1 client:download-schema`

This approach is a bit more foolproof, but also a bit more work intensive as it redownloads the deps when it's run. I recommend specifying the version in the command as I have, else it will always use `latest` and you'll have no control over which version you use.

**Comment by Siyfion** [comment]
@trevor-scheer Thanks for your detailed response!

I can confirm that the Gatsby Starter Blog project doesn't include `apollo` (as standard), but that `gatsby` itself is clearly using `graphql` under the hood. As such, using the `npx apollo@2.11.1 client:download-schema` method worked perfectly, as described. 👍
