### ISSUE TITLE
Errors with directory names that look like files (.ts/.js)

### ISSUE THREAD

**Issue by KurokiUrabe** [apollographql/apollo-tooling#1311]
**note:**
my editor format base.js so the line is not 109 is 94.
maybe this is more a feature not documented, let me know.

**Intended outcome:**
Having a folder with a name extension include in base.js>fileAssociations  show a warning, error with a file name would be nice

this happened using Apollo GraphQL for VS Code  and someone name a folder char.js

**Actual outcome:**

{ Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:632:3)
    at tryReadSync (fs.js:472:20)
    at Object.fs.readFileSync (fs.js:513:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at GraphQLClientProject.fileDidChange (/home/kurabe/.vscode/extensions/apollographql.vscode-apollo-1.7.1/node_modules/apollo-language-server/lib/project/base.js:109:29)
    at connection.onDidChangeWatchedFiles.params (/home/kurabe/.vscode/extensions/apollographql.vscode-apollo-1.7.1/node_modules/apollo-language-server/lib/server.js:95:25)
    at handleNotification (/home/kurabe/.vscode/extensions/apollographql.vscode-apollo-1.7.1/node_modules/vscode-jsonrpc/lib/main.js:489:43)
    at processMessageQueue (/home/kurabe/.vscode/extensions/apollographql.vscode-apollo-1.7.1/node_modules/vscode-jsonrpc/lib/main.js:260:17)
    at Immediate.setImmediate [as _onImmediate] (/home/kurabe/.vscode/extensions/apollographql.vscode-apollo-1.7.1/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at runCallback (timers.js:696:18) errno: -21, syscall: 'read', code: 'EISDIR' }

**How to reproduce the issue:**
name a folder  with some of the extension of base.js>fileAssociations 

**Versions**
apollographql.vscode-apollo-1.7.1 with  apollo-language-server v1.9.1

**Comment by JakeDawkins** [comment]
Hi! Thanks for opening this. Is this still an issue? I'm having a little trouble understanding what the problem you're running into here is. Can you please provide a simple reproduction repository that fails this?

**Comment by joonhocho** [comment]
@JakeDawkins  This issue still exists. It happens when a directory name has an extensions (suffix) like '.ts', '.js' .
For example, I have a type definition file named `src/@types/dinero.js/index.d.ts`. Since the file name path a directory `dinero.js` which looks like a file name, it causes this error.

**Comment by JakeDawkins** [comment]
Ah, that makes sense. Thanks for clarifying @joonhocho. I imagine this is a fairly rare case (where people have .js/.ts in their directory names) so I probably won't be able to prioritize this work soon.
