### ISSUE TITLE
Syntax error in .graphql file not reported directly

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-tooling#1436]
**Intended outcome:**
When there's a syntax error in a file, tell us what file the syntax error is in. 

**Actual outcome:**

In [iOS 664](https://github.com/apollographql/apollo-ios/issues/664), a user was trying to figure out why their code wasn't compiling, and was getting a ton of errors about a missing fragment.  The actual problem was the the `.graphql` file which contained that fragment had a syntax error, and the type wasn't getting parsed. There was no indication which file had the error, or that an error even existed. 

**How to reproduce the issue:**

[Emailing schema and `graphql` files internally]

**Versions**

2.16.x

**Comment by designatednerd** [comment]
Looks like this is also related to [iOS 667](https://github.com/apollographql/apollo-ios/issues/667)

**Comment by pm-dev** [comment]
Got this error when adding a fragment with 4 dots `....` instead of 3 `...`
Not the best error messaging

**Comment by scottwillman** [comment]
This definitely is making debugging more difficult. What file has the error?
```
MacBook-Pro:mission-backend scottwillman$ yarn start
yarn run v1.22.4
$ node -r esm index.js
/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/error/syntaxError.js:1
GraphQLError: Syntax Error: Expected Name, found "{".
    at syntaxError (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:1423:40)
    at Parser.parseName (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:92:22)
    at Parser.parseNamedType (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:668:18)
    at Parser.parseTypeReference (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:646:19)
    at Parser.parseFieldDefinition (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:872:21)
    at Parser.optionalMany (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:1516:28)
    at Parser.parseFieldsDefinition (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:858:17)
    at Parser.parseObjectTypeDefinition (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:806:23)
    at Parser.parseTypeSystemDefinition (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:702:23)
    at Parser.parseDefinition (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:144:23)
    at Parser.many (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:1537:26)
    at Parser.parseDocument (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:109:25)
    at parse (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql/language/parser.js:36:17)
    at parseDocument (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql-tag/lib/graphql-tag.umd.js:135:16)
    at gql (/Users/scottwillman/Desktop/mission/mission/mission-backend/node_modules/graphql-tag/lib/graphql-tag.umd.js:176:10) {
  message: 'Syntax Error: Expected Name, found "{".',
  locations: [ { line: 31, column: 17 } ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
