### ISSUE TITLE
ServerParseError: Unexpected token G in JSON at position 0

### ISSUE THREAD

**Issue by Maxpain177** [apollographql/apollo-tooling#1565]
**Intended outcome:**

I'm trying to upload our schema to Apollo Graph Manager:
`apollo service:push --endpoint http://api.mysite.net`

**Actual outcome:**
```
  ✔ Loading Apollo Project
  ✖ Uploading service to Engine
    → Unexpected token G in JSON at position 0
ServerParseError: Unexpected token G in JSON at position 0
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/apollo/node_modules/apollo-link-http-common/lib/index.js:35:25
```

But if I use https instead of http it is working fine.
Example:
```
apollo service:push --endpoint https://api.mysite.net
  ✔ Loading Apollo Project
  ✔ Uploading service to Engine


No change in schema from previous version

╔════════╤═════════╤═════════╗
║ id     │ graph   │ tag     ║
╟────────┼─────────┼─────────╢
║ dc132f │ FASTCUP │ current ║
╚════════╧═════════╧═════════╝
```

**Versions**

apollo/2.19.0 darwin-x64 node-v12.11.0

**Comment by JakeDawkins** [comment]
Hmm... This doesn't _seem_ right to me. Can you provide a reproduction or even a public endpoint that I can introspect against to debug? Otherwise, i'd really like to see the raw response from the server

**Comment by Maxpain177** [comment]
@JakeDawkins we have the redirect from `http` to `https`

**Comment by SaigeXSaige** [comment]
Adding to this issue. I added `https` after experiencing the issue above and received this response: `yarn global v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "apollo > apollo-language-server > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@8.5.0" has unmet peer dependency "typescript@>=2.0".
[4/4] Building fresh packages...
success Installed "apollo@2.21.0" with binaries:
      - apollo
Done in 2.49s.
  ✔ Loading Apollo Project
  ✖ Uploading service to Engine
    → request to https://localhost:4000/api failed, reason: write EPROTO 140700675303232:error:140770FC:SSL routines:SSL23_G
…
FetchError: request to https://localhost:4000/api failed, reason: write EPROTO 140700675303232:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:
    at ClientRequest.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/node-fetch/lib/index.js:1455:11)
C02X207RJHD4:passport sleslie$ `
