### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by MitchK** [apollographql/apollo-tooling#1587]
**Intended outcome:**

When generating TypeScript bindings, it should throw no error or warning messages.

**Actual outcome:**

After upgrade to MacOS Catalina, when generating TypeScript bindings, it throws this error:
```
$ apollo codegen:generate --excludes=node_modules/* --includes=**/*.tsx --target typescript --tagName gql --outputFlat src/__generated__ --endpoint https://myendpoint/api
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:517:3)
    at tryReadSync (fs.js:342:20)
    at Object.readFileSync (fs.js:379:19)
    at GraphQLClientProject.fileDidChange (/Users/user/github.com/MitchK/repo/node_modules/apollo-language-server/lib/project/base.js:98:35)
    at /Users/user/github.com/MitchK/repo/node_modules/apollo-language-server/lib/project/base.js:87:22
    at GraphQLClientProject.scanAllIncludedFiles (/Users/user/github.com/MitchK/repo/node_modules/apollo-language-server/lib/project/base.js:89:11)
    at GraphQLClientProject.initialize (/Users/user/github.com/MitchK/repo/node_modules/apollo-language-server/lib/project/client.js:60:22)
    at new GraphQLProject (/Users/user/github.com/MitchK/repo/node_modules/apollo-language-server/lib/project/base.js:39:46)
    at new GraphQLClientProject (/Users/user/github.com/MitchK/repo/node_modules/apollo-language-server/lib/project/client.js:35:9)
    at Generate.createService (/Users/user/github.com/MitchK/repo/node_modules/apollo/lib/Command.js:130:28) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
  ✔ Loading Apollo Project
  ✔ Generating query files with 'typescript' target - wrote 12 files
✨  Done in 9.25s.
```

**How to reproduce the issue:**

1. Use MacOS Catalina
2. Use Apollo 2.19.1
3. Run ```apollo codegen:generate --excludes=node_modules/* --includes=**/*.tsx --target typescript --tagName gql --outputFlat src/__generated__ --endpoint https://myendpoint/api```

**Versions**

- MacOS Catalina
- Yarn 1.19.1
- Apollo 2.19.1
- apollo-language-server 1.16.1

**Comment by MitchK** [comment]
Nvm, I had a directory somewhere buried in my folder structure that accidentally got the .tsx ending. Therefore, it would try to open the directory like a file.
