### ISSUE TITLE
Swift: Can't specify null in query

### ISSUE THREAD

**Issue by cltnschlosser** [apollographql/apollo-tooling#1592]
**Intended outcome:**
Works correctly.

**Actual outcome:**
Codegen error:
```
→ Cannot read property 'kind' of null
TypeError: Cannot read property 'kind' of null
    at expressionFromValue (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:159:23)
    at language_1.SwiftSource.wrap.language_1.SwiftSource.join.Object.entries.map (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:167:87)
    at Array.map (<anonymous>)
    at expressionFromValue (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:166:124)
    at language_1.SwiftSource.wrap.language_1.SwiftSource.join.args.map.arg (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:178:84)
    at Array.map (<anonymous>)
    at Helpers.dictionaryLiteralForFieldArguments (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/helpers.js:177:99)
    at withIndent (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-swift/lib/codeGeneration.js:499:79)
    at GeneratedFile.withIndent (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-core/lib/utilities/CodeGenerator.js:54:9)
    at SwiftAPIGenerator.withIndent (path/Pods/Apollo/scripts/apollo/node_modules/apollo-codegen-core/lib/utilities/CodeGenerator.js:109:26)
```

**How to reproduce the issue:**
This should help in making a testcase.
```
const schema = buildSchema(`
         schema {
           query: Query
         }
         type Query {
           foo(input: FooInput!): Int
         }
         input FooInput {
           id: ID
         }
       `);
       const document = parse(`
         query FieldArgumentsWithEmptyInputObject {
           foo(input: { id: null }) {
             id
           }
         }
       `);
```

**Comment by designatednerd** [comment]
@lilyball Do you have any bandwidth to take a look at this issue? At this point you're more familiar with this code than I am

**Comment by lilyball** [comment]
The value itself is `null`. I assume this is coming from somewhere outside of `apollo-codegen-swift`, but I'll try to find the time to diagnose it at least.

**Comment by lilyball** [comment]
Looks like field arguments are typed as `any` but the compiler could in fact produce `number | null | any[] | {} | { kind: "Variable", variableName: string } | string | boolean`. It's just not typed this way. For most of these types, accessing the field `.kind` will just return `undefined`, it's really just `null` that's a problem.

What I'd really like to do is fix the typing here to not use `any`, but I feel like that might be a pretty wide-ranging change.

**Comment by lilyball** [comment]
> What I'd really like to do is fix the typing here to not use `any`, but I feel like that might be a pretty wide-ranging change.

Turns out it's impossible because you can't write e.g. `type Foo = number | Foo[]`. Apparently a type alias can only refer to types that could otherwise be written without the type alias.

**Comment by lilyball** [comment]
Looks like [TypeScript 3.7 fixes](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#more-recursive-type-aliases) the issue with recursive type aliases.
