### ISSUE TITLE
Error: Unknown type: "AWSDateTime"

### ISSUE THREAD

**Issue by ivands** [apollographql/apollo-tooling#1600]
I'm using AWS AppSync to write my graphql service.
AppSync supports more types out of the box like: AWSDateTime.
But in the apollo vscode plugin I get the following error:
`UnhandledPromiseRejectionWarning: Error: Unknown type: "AWSDateTime".`
Does this plugin not work with AWS or custom types?
Or is this a bug?

Im using version: 1.11.0
And my apollo config looks like this:
```javascript
module.exports = {
	client: {
		service: {
			name: 'gamblr',
			url: 'AWS_APPSYNC_URL',
			excludes: ['node_modules/**/*'],
			includes: ['src/**/*.graphql'],
		},
	},
};
```

**Comment by JakeDawkins** [comment]
Hey @ivands! I'm not sure what exactly is going on here. The apollo VS Code extension doesn't explicitly build in support for appsync, but the error you're seeing may be something that's still fixable by config/project setup.

Is the AWSDateTime a GraphQL type you're talking about or a typescript/other kind of type. And is it a TS/graphql type that is only present on the appsync client, or is it s type the server is aware of (I'm not that familiar with appsync setup)?

If it's a graphql type, is it introspectable from the url you provide the `client.service.url`? If the introspection query doesn't reveal that type, the extension doesn't know it exists, and you can't use it.

It'd also be helpful to see a stacktrace of the error you pasted to know more about the context of the error, as well as the operation the error was caused by.

Also, a couple notes about the config you have:

1. you shouldn't have to explicitly ignore the `node_modules` folder
2. You shouldn't need to explicitly include the `src/**/*.graphql` pattern, it should automatically include those files in the default glob we use.

**Comment by ivands** [comment]
Hey @JakeDawkins! Thanks for the info

Right now i'm just trying to make the extension work with a different endpoint:
```javascript
module.exports = {
	client: {
		service: {
			name: 'Test',
			url: 'https://api.graph.cool/simple/v1/ciyz901en4j590185wkmexyex',
		},
	},
};
```
This is the error i'm getting right now.
```
------------------------------
🚀 Apollo GraphQL v1.11.0
------------------------------
❌ Service stats could not be loaded. This may be because you're missing an apollo.config.js file or it is misconfigured. For more information about configuring Apollo projects, see the guide here (https://bit.ly/2ByILPj).
(node:20081) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Expected Name, found }
    at syntaxError (/Users/ivan/.vscode/extensions/apollographql.vscode-apollo-1.11.0/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (/Users/ivan/.vscode/extensions/apollographql.vscode-apollo-1.11.0/node_modules/graphql/language/parser.js:1404:40)
    at Parser.parseName (/Users/ivan/.vscode/extensions/apollographql.vscode-apollo-1.11.0/node_modules/graphql/language/parser.js:94:22)
    at Parser.parseFieldDefinition (/Users/ivan/.vscode/extensions/apollographql.vscode-apollo-1.11.0/node_modules/graphql/language/parser.js:857:21)
    at Parser.optionalMany (/Users/ivan/.vscode/extensions/apollographql.vscode-apollo-1.11.0/node_modules/graphql/language/parser.js:1497:28)
    at Parser.parseFieldsDefinition (/Users/ivan/.vscode/extensions/apollographql.vscode-apollo-1.11.0/node_modules/graphql/language/parser.js:846:17)
    at Parser.parseInterfaceTypeDefinition (/Users/ivan/.vscode/extensions/apollographql.vscode-apollo-1.11.0/node_modules/graphql/language/parser.js:921:23)
    at Parser.parseTypeSystemDefinition (/Users/ivan/.vscode/extensions/apollographql.vscode-apollo-1.11.0/node_modules/graphql/language/parser.js:699:23)
    at Parser.parseDefinition (/Users/ivan/.vscode/extensions/apollographql.vscode-apollo-1.11.0/node_modules/graphql/language/parser.js:146:23)
    at Parser.many (/Users/ivan/.vscode/extensions/apollographql.vscode-apollo-1.11.0/node_modules/graphql/language/parser.js:1518:26)
```

**Comment by ivands** [comment]
When i try the config in a clean project the code works. So i'm guessing it's trying to parse a local file in my project that it shouldn't.

**Comment by JakeDawkins** [comment]
Ah, great point. That's not super helpful 😞 

Can you try to manually define `client.includes` and maybe only include a single file and see if it works? It's likely the default includes of all ts,js,graphql,gql,graphqls, etc files under `src` is just including too much, and there's a syntax error in a type definition/operation somewhere

Like...

```
module.exports = {
	client: {
		includes: ['src/my/test/file.ts'],
		service: {
			name: 'Test',
			url: 'https://api.graph.cool/simple/v1/ciyz901en4j590185wkmexyex',
		},
	},
};
```

**Comment by thetrav** [comment]
AWSDateTime is a scalar provided by Amazon Web Services AppSync (see https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html)

I came across this issue while looking for the correct way to configure those scalars.  
https://the-guild.dev/graphql/codegen/plugins/typescript/typescript#scalars seems relevant, however my own configuration:

```
const config: CodegenConfig = {
  schema: "../server/appsync/schema/*.graphql",
  generates: {
    "common/__generated__/": {
      preset: "client",
      plugins: ["typescript"],
      config: {
        scalars: {
          AWSDateTime: {
            input: "string",
            output: "string"
          }
        }
      }
    }
  },
  ignoreNoDocuments: true
};
```

Does not appear to be doing the trick.  I'll watch this issue and ping back if/when I resolve my own problem in case it helps

**Comment by thetrav** [comment]
ok, that was quick, https://gist.github.com/rpggio/2c56def51ac9f48c758436328a68923a held the answer to my woes.  The key piece being an extra graphql file containing all of the scalars that AWS declares which I pass in to the schema prop alongside the real schemas from my server
