### ISSUE TITLE
Unable to Download Schema - Unexpected invariant triggered

### ISSUE THREAD

**Issue by DSchechter** [apollographql/apollo-tooling#1684]
**Intended outcome:**

Being able to download a schema

**Actual outcome:**

apollo schema:download --endpoint="https://www.goldstar.com/graphql" schema.json
  ✔ Loading Apollo Project
  ✖ Saving schema to schema.json
    → Unexpected invariant triggered
Error: Unexpected invariant triggered
    at invariant (/usr/local/lib/node_modules/apollo/node_modules/graphql/jsutils/invariant.js:12:11)
    at Object.introspectionFromSchema (/usr/local/lib/node_modules/apollo/node_modules/graphql/utilities/introspectionFromSchema.js:34:95)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/service/download.js:21:82)

apollo client:download-schema --endpoint=https://www.goldstar.com/graphql schema.json
⚠️  It looks like there are 0 files associated with this Apollo Project. This may be because you don't have any files yet, or your includes/excludes fields are configured incorrectly, and Apollo can't find your files. For help configuring Apollo projects, see this guide: https://bit.ly/2ByILPj
  ⠦ Loading Apollo Project
    Saving schema to schema.json
CLIError: Error in "Loading schema for Unnamed Project": TypeError: Float cannot represent non numeric value: Infinity
    at Object.error (/usr/local/lib/node_modules/apollo/node_modules/@oclif/errors/lib/index.js:22:17)
    at SchemaDownload.error (/usr/local/lib/node_modules/apollo/node_modules/@oclif/command/lib/command.js:57:23)
    at OclifLoadingHandler.showError (/usr/local/lib/node_modules/apollo/lib/OclifLoadingHandler.js:28:22)
    at OclifLoadingHandler.handle (/usr/local/lib/node_modules/apollo/lib/OclifLoadingHandler.js:13:18)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  oclif: { exit: 2 },
  ✖ Loading Apollo Project
    → Error initializing Apollo GraphQL project "Unnamed Project": Error: Error in "Loading schema for 
…
    Saving schema to schema.json
 ›   Error: Error initializing Apollo GraphQL project "Unnamed Project": Error: Error in "Loading 
 ›   schema for Unnamed Project": TypeError: Float cannot represent non numeric value: Infinity

**How to reproduce the issue:**

I'm am using Apollo for iOS and install Apollo CLI via npm. Running the command via command line or from Xcode `"${SCRIPT_PATH}"/run-bundled-codegen.sh schema:download --endpoint="https://www.goldstar.com/graphql" schema.json`, results in the same error

**Versions**

apollo/2.21.1 darwin-x64 node-v12.6.0

**Comment by DSchechter** [comment]
Issue is not related to Apollo CLI

**Comment by designatednerd** [comment]
Full details: https://spectrum.chat/apollo/apollo-ios/unable-to-download-schema~583fa717-f840-43d6-b477-1e2fc892739f
