### ISSUE TITLE
Uploading service to Apollo Graph Manager returns 404

### ISSUE THREAD

**Issue by cstech-carl-camilleri** [apollographql/apollo-tooling#1870]
**Intended outcome:**
Trying to publish a schema coming from a NestJS (on top of Apollo) server
 
Running npx apollo service:push returns an error:
```
npx apollo service:push
 ›   Warning: [Deprecation warning] Setting the key via ENGINE_API_KEY is deprecated and will not be supported in future versions.
  ✔ Loading Apollo Project
  ✖ Uploading service to Apollo Graph Manager
    → ServerError: Response not successful: Received status code 404
Error: ServerError: Response not successful: Received status code 404
    at ~/.npm/_npx/16418/lib/node_modules/apollo/node_modules/apollo-language-server/lib/providers/schema/endpoint.js:61:19
    at async EndpointSchemaProvider.resolveSchema (~/.npm/_npx/16418/lib/node_modules/apollo/node_modules/apollo-language-server/lib/providers/schema/endpoint.js:28:35)
    at async Task.task (~/.npm/_npx/16418/lib/node_modules/apollo/lib/commands/service/push.js:71:36)
 

```

**Actual outcome:**

**How to reproduce the issue:**

**Versions**

**Comment by cstech-carl-camilleri** [comment]
Actually fixed the problem, had the following apollog.config.js:
```
module.exports = {
    service: {
      name: "projectname",
      endpoint: {
          url: 'http://localhost:3000'
      }
    }
  }
```
Replacing url with http://localhost:3000/graphql works OK
