### ISSUE TITLE
Latest published package is broken

### ISSUE THREAD

**Issue by jhanschoo** [apollographql/apollo-tooling#2033]
**Intended outcome:**

Running `npx apollo` in a new folder should print something like

```
Command line tool for Apollo GraphQL

VERSION
  apollo/2.28.3 linux-x64 node-v12.18.2

USAGE
  $ apollo [COMMAND]

COMMANDS
  client   Check a client project against a pushed service
  help     display help for apollo
  plugins  list installed plugins
  service  Check a service against known operation workloads to find breaking changes
```

**Actual outcome:**

Running `npx apollo` prints something like:

```
npm ERR! Unexpected end of JSON input while parsing near '...7AbvFzV9c3b8LG5qH5rhb'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jhanschoo/.npm/_logs/2020-07-08T00_18_15_723Z-debug.log
Install for [ 'apollo@latest' ] failed with code 1
```

The log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/jhanschoo/.nvm/versions/node/v12.18.2/bin/node',
1 verbose cli   '/home/jhanschoo/.nvm/versions/node/v12.18.2/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'apollo@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/home/jhanschoo/.npm/_npx/94425',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose npm-session aa149206ca2c0898
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/apollo 212ms (from cache)
8 silly pacote tag manifest for apollo@latest fetched in 244ms
9 timing stage:loadCurrentTree Completed in 259ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule apollo@2.28.3 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/@oclif%2fplugin-help 245ms (from cache)
18 silly pacote version manifest for @oclif/plugin-help@2.2.3 fetched in 263ms
19 silly resolveWithNewModule @oclif/plugin-help@2.2.3 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/@oclif%2fconfig 309ms (from cache)
21 silly pacote version manifest for @oclif/config@1.15.1 fetched in 323ms
22 silly resolveWithNewModule @oclif/config@1.15.1 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/@oclif%2fplugin-plugins 363ms (from cache)
24 silly pacote version manifest for @oclif/plugin-plugins@1.7.9 fetched in 378ms
25 silly resolveWithNewModule @oclif/plugin-plugins@1.7.9 checking installable status
26 http fetch GET 304 https://registry.npmjs.org/apollo-codegen-core 386ms (from cache)
27 http fetch GET 304 https://registry.npmjs.org/@oclif%2fplugin-not-found 403ms (from cache)
28 http fetch GET 304 https://registry.npmjs.org/@oclif%2ferrors 416ms (from cache)
29 http fetch GET 304 https://registry.npmjs.org/@oclif%2fcommand 430ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/@oclif%2fplugin-autocomplete 425ms (from cache)
31 silly pacote range manifest for apollo-codegen-core@^0.37.3 fetched in 414ms
32 silly resolveWithNewModule apollo-codegen-core@0.37.3 checking installable status
33 silly pacote version manifest for @oclif/errors@1.2.2 fetched in 436ms
34 silly resolveWithNewModule @oclif/errors@1.2.2 checking installable status
35 http fetch GET 304 https://registry.npmjs.org/@oclif%2fplugin-warn-if-update-available 423ms (from cache)
36 silly pacote version manifest for @oclif/plugin-not-found@1.2.4 fetched in 428ms
37 silly resolveWithNewModule @oclif/plugin-not-found@1.2.4 checking installable status
38 http fetch GET 304 https://registry.npmjs.org/apollo-codegen-flow 174ms (from cache)
39 silly pacote version manifest for @oclif/command@1.6.1 fetched in 451ms
40 silly resolveWithNewModule @oclif/command@1.6.1 checking installable status
41 silly pacote version manifest for @oclif/plugin-autocomplete@0.2.0 fetched in 457ms
42 silly resolveWithNewModule @oclif/plugin-autocomplete@0.2.0 checking installable status
43 silly pacote version manifest for @oclif/plugin-warn-if-update-available@1.7.0 fetched in 456ms
44 silly resolveWithNewModule @oclif/plugin-warn-if-update-available@1.7.0 checking installable status
45 silly pacote range manifest for apollo-codegen-flow@^0.35.3 fetched in 206ms
46 silly resolveWithNewModule apollo-codegen-flow@0.35.3 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/apollo-codegen-scala 244ms (from cache)
48 silly fetchPackageMetaData error for apollo-codegen-scala@^0.36.3 Unexpected end of JSON input while parsing near '...7AbvFzV9c3b8LG5qH5rhb'
49 http fetch GET 304 https://registry.npmjs.org/apollo-codegen-swift 269ms (from cache)
50 http fetch GET 304 https://registry.npmjs.org/apollo-codegen-typescript 244ms (from cache)
51 silly pacote range manifest for apollo-codegen-swift@^0.37.3 fetched in 285ms
52 silly resolveWithNewModule apollo-codegen-swift@0.37.3 checking installable status
53 http fetch GET 304 https://registry.npmjs.org/apollo-graphql 234ms (from cache)
54 silly pacote range manifest for apollo-codegen-typescript@^0.37.3 fetched in 274ms
55 silly resolveWithNewModule apollo-codegen-typescript@0.37.3 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/apollo-language-server 263ms (from cache)
57 http fetch GET 304 https://registry.npmjs.org/env-ci 242ms (from cache)
58 silly pacote range manifest for apollo-graphql@^0.4.5 fetched in 278ms
59 silly resolveWithNewModule apollo-graphql@0.4.5 checking installable status
60 http fetch GET 304 https://registry.npmjs.org/chalk 263ms (from cache)
61 silly pacote range manifest for apollo-language-server@^1.22.3 fetched in 281ms
62 silly resolveWithNewModule apollo-language-server@1.22.3 checking installable status
63 http fetch GET 304 https://registry.npmjs.org/cli-ux 267ms (from cache)
64 silly pacote version manifest for env-ci@3.2.2 fetched in 262ms
65 silly resolveWithNewModule env-ci@3.2.2 checking installable status
66 silly pacote version manifest for chalk@2.4.2 fetched in 295ms
67 silly resolveWithNewModule chalk@2.4.2 checking installable status
68 silly pacote version manifest for cli-ux@5.4.6 fetched in 296ms
69 silly resolveWithNewModule cli-ux@5.4.6 checking installable status
70 http fetch GET 304 https://registry.npmjs.org/gaze 255ms (from cache)
71 silly pacote version manifest for gaze@1.1.3 fetched in 282ms
72 silly resolveWithNewModule gaze@1.1.3 checking installable status
73 http fetch GET 304 https://registry.npmjs.org/git-parse 318ms (from cache)
74 http fetch GET 304 https://registry.npmjs.org/git-rev-sync 300ms (from cache)
75 silly pacote version manifest for git-parse@1.0.4 fetched in 332ms
76 silly resolveWithNewModule git-parse@1.0.4 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/git-url-parse 302ms (from cache)
78 silly pacote version manifest for git-rev-sync@2.0.0 fetched in 334ms
79 silly resolveWithNewModule git-rev-sync@2.0.0 checking installable status
80 silly pacote range manifest for git-url-parse@^11.1.2 fetched in 348ms
81 silly resolveWithNewModule git-url-parse@11.1.2 checking installable status
82 http fetch GET 304 https://registry.npmjs.org/glob 346ms (from cache)
83 http fetch GET 304 https://registry.npmjs.org/listr 316ms (from cache)
84 http fetch GET 304 https://registry.npmjs.org/graphql-tag 340ms (from cache)
85 silly pacote version manifest for glob@7.1.5 fetched in 369ms
86 silly resolveWithNewModule glob@7.1.5 checking installable status
87 http fetch GET 304 https://registry.npmjs.org/graphql 366ms (from cache)
88 silly pacote version manifest for listr@0.14.3 fetched in 346ms
89 silly resolveWithNewModule listr@0.14.3 checking installable status
90 silly pacote version manifest for graphql-tag@2.10.3 fetched in 366ms
91 silly resolveWithNewModule graphql-tag@2.10.3 checking installable status
92 silly pacote range manifest for graphql@14.0.2 - 14.2.0 || ^14.3.1 fetched in 390ms
93 silly resolveWithNewModule graphql@14.7.0 checking installable status
94 http fetch GET 304 https://registry.npmjs.org/@apollographql%2fapollo-tools 1188ms (from cache)
95 http fetch GET 304 https://registry.npmjs.org/lodash.identity 311ms (from cache)
96 silly pacote range manifest for @apollographql/apollo-tools@^0.4.8 fetched in 1209ms
97 silly resolveWithNewModule @apollographql/apollo-tools@0.4.8 checking installable status
98 silly pacote version manifest for lodash.identity@3.0.0 fetched in 337ms
99 silly resolveWithNewModule lodash.identity@3.0.0 checking installable status
100 http fetch GET 304 https://registry.npmjs.org/lodash.pickby 229ms (from cache)
101 http fetch GET 304 https://registry.npmjs.org/mkdirp 208ms (from cache)
102 silly pacote version manifest for lodash.pickby@4.6.0 fetched in 241ms
103 silly resolveWithNewModule lodash.pickby@4.6.0 checking installable status
104 http fetch GET 304 https://registry.npmjs.org/moment 180ms (from cache)
105 silly pacote version manifest for mkdirp@0.5.5 fetched in 217ms
106 silly resolveWithNewModule mkdirp@0.5.5 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/strip-ansi 157ms (from cache)
108 silly pacote version manifest for moment@2.26.0 fetched in 189ms
109 silly resolveWithNewModule moment@2.26.0 checking installable status
110 http fetch GET 304 https://registry.npmjs.org/table 139ms (from cache)
111 http fetch GET 304 https://registry.npmjs.org/tty 140ms (from cache)
112 http fetch GET 304 https://registry.npmjs.org/vscode-uri 131ms (from cache)
113 silly pacote version manifest for strip-ansi@5.2.0 fetched in 166ms
114 silly resolveWithNewModule strip-ansi@5.2.0 checking installable status
115 silly pacote version manifest for table@5.4.6 fetched in 149ms
116 silly resolveWithNewModule table@5.4.6 checking installable status
117 silly pacote version manifest for tty@1.0.1 fetched in 150ms
118 silly resolveWithNewModule tty@1.0.1 checking installable status
119 silly pacote version manifest for vscode-uri@1.0.6 fetched in 140ms
120 silly resolveWithNewModule vscode-uri@1.0.6 checking installable status
121 http fetch GET 304 https://registry.npmjs.org/apollo-env 847ms (from cache)
122 silly pacote range manifest for apollo-env@^0.6.5 fetched in 853ms
123 silly resolveWithNewModule apollo-env@0.6.5 checking installable status
124 timing stage:rollbackFailedOptional Completed in 1ms
125 timing stage:runTopLevelLifecycles Completed in 1581ms
126 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...7AbvFzV9c3b8LG5qH5rhb'
126 verbose stack     at JSON.parse (<anonymous>)
126 verbose stack     at parseJson (/home/jhanschoo/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
126 verbose stack     at /home/jhanschoo/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
126 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
127 verbose cwd /home/jhanschoo/src/writerite
128 verbose Linux 5.4.0-40-generic
129 verbose argv "/home/jhanschoo/.nvm/versions/node/v12.18.2/bin/node" "/home/jhanschoo/.nvm/versions/node/v12.18.2/lib/node_modules/npm/bin/npm-cli.js" "install" "apollo@latest" "--global" "--prefix" "/home/jhanschoo/.npm/_npx/94425" "--loglevel" "error" "--json"
130 verbose node v12.18.2
131 verbose npm  v6.14.5
132 error Unexpected end of JSON input while parsing near '...7AbvFzV9c3b8LG5qH5rhb'
133 verbose exit [ 1, true ]
```

**How to reproduce the issue:**

Run `npx apollo` in a new folder.

**Versions**

* node v12.18.2
* npm  v6.14.5
* apollo 2.28.3

**Comment by jhanschoo** [comment]
My bad, this error was caused by corrupt cache.
