### ISSUE TITLE
Warnings during service:push in Node v14.8.0 with the CLI

### ISSUE THREAD

**Issue by tvvignesh** [apollographql/apollo-tooling#2100]
**Intended outcome:**

I was pushing the schema using `service:push` to apollo studio using `npx apollo service:push --graph=tc-graph --key=service:tokenhere --variant=current --serviceName=svc-name --serviceURL=http://localhost:port/ --localSchemaFile=./path/to/GQLFile.gql`

**Actual outcome:**

<img width="595" alt="Screenshot 2020-08-29 145601" src="https://user-images.githubusercontent.com/1165845/91633718-4070e580-ea08-11ea-9046-6f43242ebc32.png">

It throws varning like this.

**How to reproduce the issue:**

I guess this has been happening with other packages as well since Node 14.x (ref: https://github.com/nodejs/node/issues/32987) and this is the PR related to it: https://github.com/nodejs/node/pull/29935

**Versions**

`apollo/2.30.3 linux-x64 node-v14.8.0`

**Comment by eduhenke** [comment]
Can confirm this, if you run with `--trace-warnings` it tells you that it's coming from the shelljs module:

```bash
$ node --trace-warnings `which apollo`  service:push --graph=GRAPHL --variant=VARIANT --serviceName=SERVICE_NAME --serviceURL=SERVICE_URL --localSchemaFile=/path/to/schema.graphql
(node:132) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:848:11)
    at Object.get (internal/modules/cjs/loader.js:862:5)
    at Object._register [as register] (/usr/local/share/.config/yarn/global/node_modules/shelljs/src/common.js:439:12)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Module.require (internal/modules/cjs/loader.js:1140:19)
    at require (internal/modules/cjs/helpers.js:75:18)
...
```
