### ISSUE TITLE
 Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by coler-j** [apollographql/apollo-tooling#2161]
**Intended outcome:**

I was trying to generate types and/or check types, or trying to use the apollo for VS code extension.

**Actual outcome:**

I receive the following error:

```
TypeError: Cannot read property 'startsWith' of undefined
    at EndpointSchemaProvider.resolveSchema (/Users/user/.vscode/extensions/apollographql.vscode-apollo-1.17.0/node_modules/apollo-language-server/lib/providers/schema/endpoint.js:23:17)
    at /Users/user/.vscode/extensions/apollographql.vscode-apollo-1.17.0/node_modules/apollo-language-server/lib/project/client.js:95:98
    at GraphQLClientProject.loadServiceSchema (/Users/user/.vscode/extensions/apollographql.vscode-apollo-1.17.0/node_modules/apollo-language-server/lib/project/client.js:100:11)
    at GraphQLClientProject.initialize (/Users/user/.vscode/extensions/apollographql.vscode-apollo-1.17.0/node_modules/apollo-language-server/lib/project/client.js:60:51)
    at new GraphQLProject (/Users/user/.vscode/extensions/apollographql.vscode-apollo-1.17.0/node_modules/apollo-language-server/lib/project/base.js:43:46)
    at new GraphQLClientProject (/Users/user/.vscode/extensions/apollographql.vscode-apollo-1.17.0/node_modules/apollo-language-server/lib/project/client.js:35:9)
    at GraphQLWorkspace.createProject (/Users/user/.vscode/extensions/apollographql.vscode-apollo-1.17.0/node_modules/apollo-language-server/lib/workspace.js:35:15)
    at /Users/user/.vscode/extensions/apollographql.vscode-apollo-1.17.0/node_modules/apollo-language-server/lib/workspace.js:73:85
    at Array.map (<anonymous>)
    at /Users/user/.vscode/extensions/apollographql.vscode-apollo-1.17.0/node_modules/apollo-language-server/lib/workspace.js:73:59
```

Seems similar to this issue: https://github.com/apollographql/apollo-tooling/issues/1513

**Versions**

`"apollo": "2.31.0"`
vs code extension: v1.17.0

**Comment by coler-j** [comment]
I am really confused. I am trying to only connect to apollo studio to grab my schema. This is my config:

```
module.exports = {
  client: {
    service: {
      name: 'Service Name',
      service: 'servicename'
    }
  }
}
```

And this is an example command I am running: `npx apollo client:codegen --target=typescript --variant=current --passthroughCustomScalars --customScalarsPrefix GraphQL --globalTypesFile=src/types/__generated__/graphql-global-types.ts __generated__`

At some point the apollo CLI is entering into [resolveSchema](https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-language-server/src/providers/schema/endpoint.ts#L25) and it tries to get a `url` from the config .... where none is defined as I am trying to connect to apollo studio.

So, seems like there is a bug.

**Comment by coler-j** [comment]
This is the `config` object that enters into [the schema provider index](https://github.com/apollographql/apollo-tooling/blame/master/packages/apollo-language-server/src/providers/schema/index.ts):

```
config {
 "rawConfig": {
  "engine": {
   "endpoint": "https://graphql.api.apollographql.com/api/graphql"
  },
  "client": {
   "includes": [
    "src/**/*.{ts,tsx,js,jsx,graphql,gql}"
   ],
   "excludes": [
    "**/node_modules",
    "**/__tests__"
   ],
   "tagName": "gql",
   "clientOnlyDirectives": [
    "connection",
    "type"
   ],
   "clientSchemaDirectives": [
    "client",
    "rest"
   ],
   "addTypename": true,
   "statsWindow": {
    "to": 0,
    "from": -86400
   },
   "service": {
    "name": "Service Name",
    "service": "servicename"
   }
  }
 },
 "configURI": {
  "$mid": 1,
  "fsPath": "/Users/user/Documents/GitHub/repo/apollo.config.js",
  "path": "/Users/user/Documents/GitHub/repo/apollo.config.js",
  "scheme": "file"
 },
 "isService": false,
 "isClient": true,
 "engine": {
  "endpoint": "https://graphql.api.apollographql.com/api/graphql"
 },
 "_graphId": "Service Name",
 "client": {
  "includes": [
   "src/**/*.{ts,tsx,js,jsx,graphql,gql}"
  ],
  "excludes": [
   "**/node_modules",
   "**/__tests__"
  ],
  "tagName": "gql",
  "clientOnlyDirectives": [
   "connection",
   "type"
  ],
  "clientSchemaDirectives": [
   "client",
   "rest"
  ],
  "addTypename": true,
  "statsWindow": {
   "to": 0,
   "from": -86400
  },
  "service": {
   "name": "Service Name",
   "service": "servicename"
  }
 },
 "_variant": "current"
}
```
