### ISSUE TITLE
Error thrown when using `client:download-schema` with a Consumer APOLLO_KEY

### ISSUE THREAD

**Issue by patrickDouglas** [apollographql/apollo-tooling#2305]
**Intended outcome:** No error thrown or some way to turn off fetching stats (as they aren't actually needed by the Consumers).

**Actual outcome:**
```
[GraphQL error]: Exception while fetching data (/service/stats) : NOT_ALLOWED_BY_USER_ROLE
Error: Exception while fetching data (/service/stats) : NOT_ALLOWED_BY_USER_ROLE
    at ApolloEngineClient.loadSchemaTagsAndFieldStats (node_modules/apollo-language-server/lib/engine/index.js:181:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async node_modules/apollo-language-server/lib/project/client.js:200:52
    at async OclifLoadingHandler.handle (node_modules/apollo/lib/OclifLoadingHandler.js:9:25)
    at async GraphQLClientProject.loadEngineData (node_modules/apollo-language-server/lib/project/client.js:198:9)
```

**How to reproduce the issue:**
Run `npx apollo client:download-schema` with a Consumer `APOLLO_KEY`

**Versions**
2.32.5

**Comment by paulpdaniels** [comment]
We noticed this as well, it seems to also occur during apollo client codegen. The codegen works but it still generates spurious errors about not being able to access stats which should be unnecessary when generating the client for the Consumer role.
