### ISSUE TITLE
Command line apollo client:codegen command fails on npm install for TTY package

### ISSUE THREAD

**Issue by jonathanpeterwu** [apollographql/apollo-tooling#2407]
**Intended outcome:**

Attempting to use the apollo codegen command fails on TTY usage

yarn dlx --quiet apollo client:codegen \
	--localSchemaFile=./packages/site-builder/src/generated/schema.graphql \
	--target=typescript \
	--customScalarsPrefix=Api \
	--passthroughCustomScalars \
	_generated 

**Actual outcome:**

Codegen command fails:

/tmp/xfs-69aa0038/dlx-2367/node_modules/cli-ux/lib/styled/table.js:285
        columns: command_1.flags.string({ exclusive: ['extended'], description: 'only show provided columns (comma-separated)' }),
                                 ^

TypeError: Cannot read property 'string' of undefined
    at /tmp/xfs-69aa0038/dlx-2367/node_modules/cli-ux/lib/styled/table.js:285:34
    at Object.<anonymous> (/tmp/xfs-69aa0038/dlx-2367/node_modules/cli-ux/lib/styled/table.js:314:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/tmp/xfs-69aa0038/dlx-2367/node_modules/cli-ux/lib/index.js:14:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
make: *** [Makefile:177: packages/site-builder/src/generated/graphql-types.ts] Error 1

**How to reproduce the issue:**

To produce run apollo client:codegen from a fresh npm build download with your local TTY dependency removed

**Comment by hoondeveloper** [comment]
Same problem +1
I am using Yarn 3 (up to berry)

**Comment by abernix** [comment]
Closed by https://github.com/apollographql/apollo-tooling/pull/2406

**Comment by nephix** [comment]
Nobody else encountering this? I use the same command in a project that uses `yarn` instead of `npm` and there it still seems to work

**Comment by nephix** [comment]
I've switched to `@graphql-codegen/cli` and it's a very good alternative
