### ISSUE TITLE
[flow] Flow modern breaks on __typename: `Property value expected type of string but got null`

### ISSUE THREAD

**Issue by kristiehowboutdat** [apollographql/apollo-tooling#443]
### Problem
Using `flow` with `0.20` breaks on the CLI with `TypeError: Property value expected type of string but got null`. This appears to be a new break, because using `flow-modern` with version `0.19` and the exact same queries and schema file does _not_ error on the CLI.

On further inspection, it seems this is coming from `__typename`s, specifically with `t.stringLiteralTypeAnnotation()` returning `null`. Noting that this was triggered on `_typename`, I tried the following (errors shown below). The only thing that worked was removing the `__typename` AND the `--addTypename` from the query. However, this is not feasible for me as we need those to refine disjoint unions. 

#### With `__typename` in the query and `--addTypename`
**Query**
```
query TestOperationQuery($operationId: String!) {
  operation(operationID: $operationId) {
  __typename
    operationID
  }
}
```

**Command**
```
$ apollo-codegen generate "src/TestQuery.graphql" --schema src/shared/graphql/generated/schema.json --target flow --addTypename --output src/types/graphql.js
```

**Error**
```
TypeError: Property value expected type of string but got null
    at Object.validate (my-repo/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at validate (my-repo/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (my-repo/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.StringLiteralTypeAnnotation (my-repo/node_modules/@babel/types/lib/builders/generated/index.js:681:31)
    at variant.possibleTypes.map.type (my-repo/node_modules/apollo-codegen-flow/src/codeGeneration.ts:339:32)
    at Array.map (<anonymous>)
    at FlowAPIGenerator.handleFieldValue (my-repo/node_modules/apollo-codegen-flow/src/codeGeneration.ts:338:10)
    at fields.map.field (my-repo/node_modules/apollo-codegen-flow/src/codeGeneration.ts:277:20)
    at Array.map (<anonymous>)
    at FlowAPIGenerator.getPropertiesForVariant (my-repo/node_modules/apollo-codegen-flow/src/codeGeneration.ts:265:19)
```

#### With `--addTypename`, removing `__typename` from the query
**Query**
```
query TestOperationQuery($operationId: String!) {
  operation(operationID: $operationId) {
    operationID
  }
}

```
**Command**
```
$ apollo-codegen generate "src/TestQuery.graphql" --schema src/shared/graphql/generated/schema.json --target flow --addTypename --output src/types/graphql.js
```
**Error**
```
TypeError: Property value expected type of string but got null
    at Object.validate (my-repo/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at validate (my-repo/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (my-repo/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.StringLiteralTypeAnnotation (my-repo/node_modules/@babel/types/lib/builders/generated/index.js:681:31)
    at variant.possibleTypes.map.type (my-repo/node_modules/apollo-codegen-flow/src/codeGeneration.ts:339:32)
    at Array.map (<anonymous>)
    at FlowAPIGenerator.handleFieldValue (my-repo/node_modules/apollo-codegen-flow/src/codeGeneration.ts:338:10)
    at fields.map.field (my-repo/node_modules/apollo-codegen-flow/src/codeGeneration.ts:277:20)
    at Array.map (<anonymous>)
    at FlowAPIGenerator.getPropertiesForVariant (my-repo/node_modules/apollo-codegen-flow/src/codeGeneration.ts:265:19)
```

#### Removing `__typename` from the query and `--addTypename` from the command
**Query**
```
query TestOperationQuery($operationId: String!) {
  operation(operationID: $operationId) {
    operationID
  }
}
```

**Command**
```
$  apollo-codegen generate "src/TestQuery.graphql" --schema src/shared/graphql/generated/schema.json --target flow --output src/types/graphql.js
```

**(No) Error**
```
Done in 0.69s.
```

### Where I looked in the code:

https://github.com/apollographql/apollo-codegen/blob/master/packages/apollo-codegen-flow/src/codeGeneration.ts#L339

https://sourcegraph.com/github.com/apollographql/apollo-codegen@aa6dc96/-/blob/packages/babel-typing/augment-babel-types.ts#L8

### Environment
    "@babel/core": "7.0.0-beta.51",
    "apollo-codegen": "0.20.0",
    "babel-plugin-import": "^1.8.0",
    "babel-plugin-lodash": "^3.3.4",
    "babel-core": "6.26.3",
    "babel-eslint": "8.2.4",
    "babel-jest": "23.0.1",
    "babel-loader": "7.1.4",
    "babel-preset-react-app": "^3.1.1",
    "babel-runtime": "6.26.0",

yarn v 1.7.0

**Comment by shadaj** [comment]
Hmm, I'm unable to reproduce this locally. The only thing I can think of is that the other packages are interacting weirdly with `apollo-codegen`. Can you try installing `apollo-codegen` globally and see if you still get that error?

**Comment by TLadd** [comment]
Just ran into this error as well, but I don't have --addTypename in my generate command. It happened after I updated to the latest v2 beta of create-react-app, so I would guess it has to do with an upgrade to a babel dependency. I'll try to get more details posted when I can.

I don't get the error when running with a globally installed version of apollo.

**Comment by michaellee8** [comment]
Strangely, I still hit this in 2020. I am able to generate the typescript files correctly when using the globally installed version, but not the one installed using yarn add --dev. Here is my toy project which one can have a look at. https://github.com/michaellee8/trans19app
