### ISSUE TITLE
Authorization header issue when downloading schema

### ISSUE THREAD

**Issue by tkallioras** [apollographql/apollo-tooling#528]
I am using apollo-cli on MacOS 10.14 beta. I am trying to run an introspection query on a local GraphQL server, however I get the following error:

`TypeError: Cannot read property 'trim' of undefined`

with the following stack:

```
TypeError: Cannot read property 'trim' of undefined
    at Object.parse (~/.nvm/versions/node/v8.11.3/lib/node_modules/apollo/lib/commands/schema/download.js:49:57)
    at Parser._flags (~/.nvm/versions/node/v8.11.3/lib/node_modules/apollo/node_modules/@oclif/parser/lib/parse.js:149:49)
    at Parser.parse (~/.nvm/versions/node/v8.11.3/lib/node_modules/apollo/node_modules/@oclif/parser/lib/parse.js:112:28)
    at Object.parse (~/.nvm/versions/node/v8.11.3/lib/node_modules/apollo/node_modules/@oclif/parser/lib/index.js:25:27)
    at SchemaDownload.parse (~/.nvm/versions/node/v8.11.3/lib/node_modules/apollo/node_modules/@oclif/command/lib/command.js:68:41)
    at SchemaDownload.run (~/.nvm/versions/node/v8.11.3/lib/node_modules/apollo/lib/commands/schema/download.js:13:38)
    at SchemaDownload._run (~/.nvm/versions/node/v8.11.3/lib/node_modules/apollo/node_modules/@oclif/command/lib/command.js:29:31)
    at <anonymous>
```

It only happens when I use an authorization header (my endpoint is accessed through an authorization token). Using the same introspection with another client and the same header, it works as expected.

**Comment by smeis** [comment]
Having the same problem, are you adding `schema.json` at the end of the command? Could you try running it without it? It's the default I think.

If that doesn't work I managed to get the schema by running this introspection query in the playground for the endpoint: https://stackoverflow.com/a/46543255

**Comment by tkallioras** [comment]
@smeis it works if I omit the schema.json parameter

**Comment by stevenqzhang** [comment]
@smeis do you know if the issue of adding `schema.json` to the end of the command is being tracked somewhere?

**Comment by smeis** [comment]
@stevenqzhang not that I know

**Comment by moonray** [comment]
Same issue with authorization token header
