### ISSUE TITLE
Codegen - Cannot read property 'getDirective' of undefined

### ISSUE THREAD

**Issue by tieorange** [apollographql/apollo-tooling#558]
Input:
`apollo codegen:generate GeneratedGraphQueries.ts --schema schema.graphql`

Output:
 ```
✔ Loading Apollo config
 ✔ Scanning for GraphQL queries (30 found)
 ✖ Generating query files with 'typescript' target
   → Cannot read property 'getDirective' of undefined
TypeError: Cannot read property 'getDirective' of undefined
    at TypeInfo.enter (/usr/local/lib/node_modules/apollo/node_modules/graphql/utilities/TypeInfo.js:137:34)
    at Object.enter (/usr/local/lib/node_modules/apollo/node_modules/graphql/language/visitor.js:363:16)
    at Object.visit (/usr/local/lib/node_modules/apollo/node_modules/graphql/language/visitor.js:254:26)
    at getValidationErrors (/usr/local/lib/node_modules/apollo/lib/validation.js:21:15)
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/lib/validation.js:26:30)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:19:18)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/codegen/generate.js:98:64)
    at Promise.resolve.then.then.skipped (/usr/local/lib/node_modules/apollo/node_modules/listr/lib/task.js:167:30)
```

I have schema.graphql file in the "src" folder

Any ideas of what is "getDirective" and why it's undefined? 
I can't find "getDirective" string in a whole project (Prism, Yoga, Postgres)

**Comment by tieorange** [comment]
schema.graphql:

```

# import ID from "./generated/prisma.graphql"
# import FeedbackGiven from "./generated/prisma.graphql"
# import FeedbackCategory from "./generated/prisma.graphql"
# import User from "./generated/prisma.graphql"
# import UserAndGroup from "./generated/prisma.graphql"
# import AuthenticateGoogleUserPayload from "./generated/prisma.graphql"

type Query {
  listUsers: [User!]!
  listGroups: UserAndGroup!
  listCategories: [FeedbackCategory!]!
  getGivenFeedback(feedbackId: ID!): FeedbackGiven
  listGivenFeedbacks: [FeedbackGiven]
  # getReceivedFeedback: Feedback
  # listReceivedFeedback: [Feedback]
  # listMessages: [FeedbackReply]
  # listFeedbackRequestThread: FeedbackThread
}

type Mutation {

  authenticateGoogleUser(
    idtoken: String!
  ): AuthenticateGoogleUserPayload!

  createSpontaneousFeedback(
    feedbackReceiverIds: [ID!]!
    title: String!
    message: String!
    categoryId: ID!
    outcomeName: FeedbackOutcomeName!
    ): FeedbackGiven
  
  createFeedbackRequest(
    requestReceiverIds: [ID!]!
    title: String!
    message: String!
    categoryId: ID!
    ): FeedbackRequest
  
  createFeedbackReply(
    feedbackRequestId: ID!
    message: String!
    outcomeName: FeedbackOutcomeName!
  ): FeedbackGiven

  createFeedbackComment(
    feedbackId: ID!
    message: String!
  ): FeedbackComment
}
```

**Comment by danilobuerger** [comment]
Could be related to https://github.com/apollographql/apollo-cli/issues/495
Can you try if it works if you inline everything instead of using import?

**Comment by cuauth** [comment]
> 
> 
> Could be related to https://github.com/apollographql/apollo-cli/issues/495
> Can you try if it works if you inline everything instead of using import?

i'm having this issue, where i can only apply directives when they are in the same file as the declaration, but the link you provided is broken. do you know any fix?
