### ISSUE TITLE
"Name in signature must be an Identifier"

### ISSUE THREAD

**Issue by murbanowicz** [apollographql/apollo-tooling#608]
I am trying to quickly generate code from TS Schema file and I am getting error: `Name in a signature must be an Identifier. (3:66)`
I am running: `apollo codegen:generate graphql.schema.ts`

The full error stack is:
```
Name in a signature must be an Identifier. (3:66)
    at _class.raise (~/.config/yarn/global/node_modules/@babel/parser/lib/index.js:3939:15)
    at _class.unexpected (~/.config/yarn/global/node_modules/@babel/parser/lib/index.js:5248:16)
    at ~/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8795:23
    at Array.map (<anonymous>)
    at _class.tsParseBindingListForSignature (~/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8793:50)
    at _class.tsFillSignature (~/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8781:35)
    at _class.tsParsePropertyOrMethodSignature (~/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8849:14)
    at _class.tsParseTypeMember (~/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8880:19)
    at _class.tsParseList (~/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8637:21)
    at _class.tsParseObjectTypeMembers (~/.config/yarn/global/node_modules/@babel/parser/lib/index.js:8896:26)
```

The file which I am using as a base is pretty simple:
```
export interface CreateUserInput {
    email?: string;
    password?: string;
}

export interface IMutation {
    createUser(createUserInput?: CreateUserInput): User | Promise<User>;
}

export interface IQuery {
    temp__(): boolean | Promise<boolean>;
}

export interface User {
    id?: number;
    email?: string;
    password?: string;
}
```

Any idea, suggestions, fixes?

**Comment by mfferreira** [comment]
I had this exact error on my project. It's not apollo related at all, but might be worth mentioning.

I had something like:
```
interface Foo {
  bar({name: string}): void
}
```
and naming the interface solves
```
interface Foo {
  bar(value: {name: string}): void
}
```

**Comment by JakeDawkins** [comment]
This issue hasn't had any traction in a while, and I can't confirm it. If this is still a blocking issue for someone, and they want to provide a reproduction, I can happily reopen :)

**Comment by eioo** [comment]
Had similar issue today as I had written declaration file for "simpleheat" library, the declaration file was:

```ts
declare module 'simpleheat' {
  export type DataPoint = [x: number, y: number, value: number];

  export interface SimpleHeat {
    data: (data: DataPoint[]) => SimpleHeat;
    draw: () => SimpleHeat;
    clear: () => SimpleHeat;
    gradient: (grad: { [stop: string]: string }) => SimpleHeat;
    max: (num = 1) => SimpleHeat;
    radius: (pointRadius = 25, blurRadius = 16) => SimpleHeat;
  }

  export default function simpleheat(canvas: HTMLCanvasElement): SimpleHeat;
}
```

I solved this by excluding all "*.d.ts" files in the "codegen.yml" file:

```yml
generates:
  src/api-types.ts:
    documents:
      - 'src/**/*.ts'
      - '!src/**/*.d.ts'
```

Hope this helps someone!
