### ISSUE TITLE
Codegen fails on schema that worked with apollo-codegen

### ISSUE THREAD

**Issue by Waitak** [apollographql/apollo-tooling#633]
I'm attempting to generate a Typescript schema as follows:
```
% apollo schema:download
      --endpoint=http://localhost:8181/graphiql \
      /tmp/document.json
% apollo codegen:generate \
       --outputFlat \
       --queries="src/app/graphql/scripts/*.gql" \
       --schema=/tmp/ \
       --target=typescript \
       /tmp/schema.ts
 ✔ Loading Apollo config
 ✔ Scanning for GraphQL queries (71 found)
 ✖ Generating query files with 'typescript' target
   → Cannot query field "lines" on type "ImmutableAddressNode"
GraphQLError: Cannot query field "lines" on type "ImmutableAddressNode"
    at Compiler.compileSelection (~/Projects/doozee-dev/frontend/doozee-frontend/node_modules/apollo-codegen-core/lib/compiler/index.js:120:27)
    at selections.selectionSetNode.selections.map.selectionNode (~/Projects/doozee-dev/frontend/doozee-frontend/node_modules/apollo-codegen-core/lib/compiler/index.js:106:76)
    at Array.map (<anonymous>)
    at Compiler.compileSelectionSet (~/Projects/doozee-dev/frontend/doozee-frontend/node_modules/apollo-codegen-core/lib/compiler/index.js:106:18)
    at Compiler.compileFragment (~/Projects/doozee-dev/frontend/doozee-frontend/node_modules/apollo-codegen-core/lib/compiler/index.js:99:32)
    at Object.compileToIR (~/Projects/doozee-dev/frontend/doozee-frontend/node_modules/apollo-codegen-core/lib/compiler/index.js:19:43)
    at Object.generate [as default] (~/Projects/doozee-dev/frontend/doozee-frontend/node_modules/apollo/lib/generate.js:74:36)
    at Task.task (~/Projects/doozee-dev/frontend/doozee-frontend/node_modules/apollo/lib/commands/codegen/generate.js:98:64)
    at Promise.resolve.then.then.skipped (~/Projects/doozee-dev/frontend/doozee-frontend/node_modules/listr/lib/task.js:167:30)
    at <anonymous>
```
It looks almost like it's not finding the schema, but it's not complaining. I'm using v1.9.2 of apollo running on Ubuntu 16.04. I've tried generating a schema for just one GraphQL file, but obtain comparable results. The generated schema and one of the GraphQL files are attached.
[files.zip](https://github.com/apollographql/apollo-cli/files/2496658/files.zip)

**Comment by martijnwalraven** [comment]
Should `--endpoint=http://localhost:8181/graphiql` be `--endpoint=http://localhost:8181/graphql` maybe?

**Comment by Waitak** [comment]
No, that part's working okay. Calling:
`% apollo schema:download --endpoint=http://localhost:8181/graphiql ...`
generates the (as far as I can tell) same document.json as:
`% apollo-codegen download-schema http://localhost:8181/graphiql ...`
It's the second call (`apollo codegen:generate`) that's failing.

**Comment by Waitak** [comment]
Further to the above, running apollo-codegen version 0.20.2 on the exact same schema produced by apollo schema:download above works without error.

**Comment by pheuter** [comment]
I'm having the same issue using a schema.json file that used to work for the same exact `codegen:generate` command.

**Comment by janhartmann** [comment]
Same issue here, reported on #648

**Comment by per06a** [comment]
Similar issue:
```prussell@ubuntu$ apollo codegen:generate --passThroughCustomScalars --schema=lean_schema.json --target typescript --queries=test_query2.graphql
 ✔ Loading Apollo config
 ✔ Scanning for GraphQL queries (1 found)
 ✖ Generating query files with 'typescript' target
   → Cannot read property 'getQueryType' of undefined
TypeError: Cannot read property 'getQueryType' of undefined
    at TypeInfo.enter (/usr/local/lib/node_modules/apollo/node_modules/graphql/utilities/TypeInfo.js:142:25)
    at Object.enter (/usr/local/lib/node_modules/apollo/node_modules/graphql/language/visitor.js:363:16)
    at Object.visit (/usr/local/lib/node_modules/apollo/node_modules/graphql/language/visitor.js:254:26)
    at getValidationErrors (/usr/local/lib/node_modules/apollo/lib/validation.js:21:15)
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/lib/validation.js:27:30)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:19:18)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/codegen/generate.js:116:64)
    at Promise.resolve.then.then.skipped (/usr/local/lib/node_modules/apollo/node_modules/listr/lib/task.js:167:30)
```
This happens on a machine-generated subset Schema (ie `lean_schema`) of a much larger Schema. The code generation does work with the larger Schema.

Main issue seems to actually be that the `schema` variable is undefined when passed to Task.task. If you debug through, the set.ctx variable doesn't have a 'schema' field:
```json
{
  "documentPaths": [
    "/home/prussell/proj/prussell-scratch/graphql_and_schema/test_query2.graphql"
  ],
  "originalSet": {
    "schema": "default",
    "includes": [
      "test_query2.graphql"
    ],
    "excludes": [
      "node_modules/**"
    ]
  }
}
```
**Why** the schema is undefined at this point is unclear, all Types are accounted for and the Type graph is enclosed (ie no Types are referenced other than those defined in the Schema).

If nothing else it would be helpful if a check could be added somewhere for the missing Schema.

**Comment by per06a** [comment]
My issue is from the GraphQL lib parsing of the lean schema. Main issue with Apollo is that the errors from `require('graphql')` don't make it to the top-level error messages. Instead `undefined` gets passed back from some wrapping code and errors then occur down-stream when the code-gen code is invoked.

For anyone with these sorts of issues, try using this snippet to directly parse your Schema using `require('graphql'`:
```javascript
// This file path will vary with your Node/NPM/etc installation
const fetch_schema = require('/usr/local/lib/node_modules/apollo/lib/fetch-schema.js');
const fs = require('fs');

async function loadAndParseSchema(schemaFilePath) {
    var x = await fetch_schema.fromFile(schemaFilePath);
    console.log(x);
}
var res = loadAndParseSchema('$PATH_TO_YOUR_SCHEMA.json');
console.log(res);
```
This just invokes the Apollo function that calls Facebook's GraphQL lib. You'll get the full stack trace if the error is here.

**Comment by JakeDawkins** [comment]
This issue hasn't seen much traction in a while, and doesn't address a specific issue. Questions like this (if they still come up) are best posted in the [spectrum community](https://spectrum.chat/apollo)
