### ISSUE TITLE
VS Code extension self signed certificate error

### ISSUE THREAD

**Issue by amaline** [apollographql/apollo-tooling#674]
Testing the new VS Code extension I received the following error:
```
Error: request to https://engine-graphql.apollographql.com/api/graphql failed, reason: self signed certificate in certificate chain
```
It does not seem to be impacted by the VS Code settings.json entry of: 
```
"http.proxyStrictSSL": false
```
in either the user or workspace settings.  We do have an enterprise intercepting proxy with a self signed certificate.

**Comment by amaline** [comment]
Seems like a well known problem with vscode

https://github.com/Microsoft/vscode/issues/12588

**Comment by cgatian** [comment]
Looks like the extension needs to abide by the proxy settings in order for this to work?

https://github.com/Microsoft/vscode/issues/67223#issuecomment-458287846

**Comment by cgatian** [comment]
@amaline I think this is actually an issue with the extension according to the comment above. Could you reopen?

**Comment by amaline** [comment]
Re-opened on request from @cgatian

**Comment by deepankar-j** [comment]
Is there any update on this issue?  It prevents me from being able to use this awesome VSCode extension at work :(.  It works fine at home.


```
[Network Error]: FetchError: request to https://engine-graphql.apollographql.com/api/graphql failed, reason: self signed certificate in certificate chain
{ Error: request to https://engine-graphql.apollographql.com/api/graphql failed, reason: self signed certificate in certificate chain
    at ApolloEngineClient.didEncounterError (/Users/dj.jain/.vscode/extensions/apollographql.vscode-apollo-1.5.2/node_modules/apollo-language-server/lib/engine/GraphQLDataSource.js:44:31)
    at ApolloEngineClient.executeSingleOperation (/Users/dj.jain/.vscode/extensions/apollographql.vscode-apollo-1.5.2/node_modules/apollo-language-server/lib/engine/GraphQLDataSource.js:52:18)
    at process._tickCallback (internal/process/next_tick.js:68:7) extensions: { code: undefined } }
[Network Error]: FetchError: request to https://engine-graphql.apollographql.com/api/graphql failed, reason: self signed certificate in certificate chain
(node:18669) UnhandledPromiseRejectionWarning: Error: request to https://engine-graphql.apollographql.com/api/graphql failed, reason: self signed certificate in certificate chain
    at ApolloEngineClient.didEncounterError (/Users/dj.jain/.vscode/extensions/apollographql.vscode-apollo-1.5.2/node_modules/apollo-language-server/lib/engine/GraphQLDataSource.js:44:31)
    at ApolloEngineClient.executeSingleOperation (/Users/dj.jain/.vscode/extensions/apollographql.vscode-apollo-1.5.2/node_modules/apollo-language-server/lib/engine/GraphQLDataSource.js:52:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18669) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18669) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by adolfox** [comment]
Having this issue on work laptop too.  I'm behind a firewall.  None of the other extensions throw any errors.  The output for the VS Intellicode extension is: 

Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Couldn't reach service Error Message: self signed certificate in certificate chain, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
None of the cached models match.
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings. Error Message: self signed certificate in certificate chain, (Error)
No model available for Python, cannot continue.
