### ISSUE TITLE
apollo service:download fails

### ISSUE THREAD

**Issue by divjose** [apollographql/apollo-tooling#677]
I am trying to download the schema using the apollo:service but it fails with the following issue:

`npx run apollo service:download graphql-schema.json --endpoint=https://easybridge-aggregation-service.nightly.realizedev-test.com/graphql`
npx: installed 5 in 2.113s
Watching /Users/ujosedi/Programs/ole/export/home/apps/easybridge-web and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
Found & ignored ./.git ; is listed in .gitignore
Found & ignored ./.idea ; is listed in .gitignore
Found & ignored ./coverage ; is listed in .gitignore
Found & ignored ./dist ; is listed in .gitignore
Found & ignored ./e2e ; is listed in .gitignore
Found & ignored ./node_modules ; is listed in .gitignore
Found & ignored ./src ; is listed in .gitignore
Found & ignored ./DESIGN.md ; is listed in .gitignore
Found & ignored ./README.md ; is listed in .gitignore
Found & ignored ./angular.json ; is listed in .gitignore
Found & ignored ./karma.conf.js ; is listed in .gitignore
Found & ignored ./package-lock.json ; is listed in .gitignore
Found & ignored ./package.json ; is listed in .gitignore
Found & ignored ./tsconfig.json ; is listed in .gitignore
Found & ignored ./tslint.json ; is listed in .gitignore

Starting: apollo service:download graphql-schema.json --endpoint=https://easybridge-aggregation-service.nightly.realizedev-test.com/graphql
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/Users/ujosedi/Programs/ole/export/home/apps/easybridge-web/apollo'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

using apollo version
apollo -v
apollo/2.0.8 darwin-x64 node-v10.2.1

any idea why it is looking for apollo folder in the main repo?

**Comment by divjose** [comment]
resolved by using just the apollo command 
`apollo service:download ./easybridge-web/graphql-schemas.json --endpoint=https://easybridge-aggregation-service.nightly.realizedev-test.com/graphql`

**Comment by Narayane** [comment]
Hi,

I still have a problem with service:download.

**Comment by Narayane** [comment]
Hi,

I still have a problem with `npx apollo service:download --endpoint=myendpoint/graphql ../schema.json`

```
$ npm list --depth=0
angel-ios@1.0.0 /Users/sebastien/LibertyRider/Workspace/ios-app/scripts
├── apollo@2.6.0
├── graphql@0.13.2
├── graphql-cli@3.0.11
├── npm@6.9.0
└── npx@10.2.0
```

When I run it with npx, I have this message in my console

```
⚠️  It looks like there are 0 files associated with this Apollo Project. This may be because you don't have any files yet, or your includes/excludes fields are configured incorrectly, and Apollo can't find your files. For help configuring Apollo projects, see this guide: https://bit.ly/2ByILPj
  ✔ Loading Apollo Project
  ✖ Saving schema to ../schema.json
    → spurious results.
Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.
Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.
https://yarnpkg.com/en/docs/selective-version-resolutions
Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (~/Workspace/ios-app/scripts/node_modules/apollo/node_modules/graphql/jsutils/instanceOf.js:37:13)
    at isSchema (~/Workspace/ios-app/scripts/node_modules/apollo/node_modules/graphql/type/schema.js:34:34)
    at assertSchema (~/Workspace/ios-app/scripts/node_modules/apollo/node_modules/graphql/type/schema.js:38:4)
    at validateSchema (~/Workspace/ios-app/scripts/node_modules/apollo/node_modules/graphql/type/validate.js:51:28)
    at assertValidSchema (~/Workspace/ios-app/scripts/node_modules/apollo/node_modules/graphql/type/validate.js:75:16)
    at assertValidExecutionArguments (~/Workspace/ios-app/scripts/node_modules/apollo/node_modules/graphql/execution/execute.js:146:35)
    at executeImpl (~/Workspace/ios-app/scripts/node_modules/apollo/node_modules/graphql/execution/execute.js:67:3)
    at execute (~/Workspace/ios-app/scripts/node_modules/apollo/node_modules/graphql/execution/execute.js:62:229)
    at Object.introspectionFromSchema (~/Workspace/ios-app/scripts/node_modules/apollo/node_modules/graphql/utilities/introspectionFromSchema.js:38:37)
    at Task.task (~/Workspace/ios-app/scripts/node_modules/apollo/lib/commands/service/download.js:16:78)
```

However, `npx apollo client:check --tag=mytag --key=mykey --includes="../**/*.graphql"` runs without problem with the same config...

Does anyone help me?
