### ISSUE TITLE
Using a localhost url: TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by pmwisdom** [apollographql/apollo-tooling#852]
I get this error every time I run `Apollo: reload schema`

 Here is my `apollo.config.js` at the top of my project.

```
module.exports = {
	client: {
		service: {
			url: "http://localhost:4000/graphql"
		}
	}
};

```

**Comment by henry74** [comment]
Getting a similar error when I run: `yarn apollo client:codegen --target typescript --outputFlat --endpoint=http//localhost:4001/graphql --addTypename`

```bash
 Error: Error in "Loading schema for Unnamed Project": TypeError: Only absolute URLs are supported
    at Object.error (/Users/hhwangbo001/Documents/snow/widget-client/node_modules/@oclif/errors/lib/index.js:22:17)
    at Generate.error (/Users/hhwangbo001/Documents/snow/widget-client/node_modules/@oclif/command/lib/command.js:47:23)
    at OclifLoadingHandler.showError (/Users/hhwangbo001/Documents/snow/widget-client/node_modules/apollo/lib/OclifLoadingHandler.js:28:22)
    at OclifLoadingHandler.handle (/Users/hhwangbo001/Documents/snow/widget-client/node_modules/apollo/lib/OclifLoadingHandler.js:13:18)
    at <anonymous> oclif: { exit: 2 }, code: undefined }
  ✖ Loading Apollo Project
    → Error initializing Apollo GraphQL project "Unnamed Project": Error: Error in "Loading schema for Unnamed Project": TypeError: Only absolute URLs are supported
    Generating query files
 ›   Error: Error initializing Apollo GraphQL project "Unnamed Project": Error: Error in "Loading schema for Unnamed Project": TypeError: Only absolute URLs are supported
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Relevant version:
```bash
yarn apollo -v
yarn run v1.13.0
$ /Users/hhwangbo001/Documents/snow/widget-client/node_modules/.bin/apollo -v
apollo/2.4.4 darwin-x64 node-v8.15.0
```

**Comment by JakeDawkins** [comment]
@henry74 it looks like your copied command was missing a `:` after `http`. 

@pmwisdom are you still having issues with this?

**Comment by CentaurWarchief** [comment]
@JakeDawkins I'm running into the same thing. Here's my apollo.config.js:

```JS
module.exports = {
  client: {
    service: {
      url: "http://localhost:4000"
    },
    includes: ["./pages/**/*.{js,jsx,graphql}"]
  }
};
```

**Comment by CentaurWarchief** [comment]
```
(node:20548) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
```

**Comment by pmwisdom** [comment]
@JakeDawkins Yes still having this issue

**Comment by pmwisdom** [comment]
I take that back, I completely reinstalled the plugin and it finally worked for me upon reloading the schema.

**Comment by CentaurWarchief** [comment]
> I take that back, I completely reinstalled the plugin and it finally worked for me upon reloading the schema.

Yeah me too—just reinstalled and it worked. All good from here!

**Comment by JakeDawkins** [comment]
Great! Glad to hear it. And thanks for checking. I'll go ahead and close this then 🎉

**Comment by ajrussellaudio** [comment]
For anyone still dropping in from a search, the command `Developer: Reload Window` from the VS Code Command Palette will fix this issue and avoid having to reinstall the extension 🎉

**Comment by ejames17** [comment]
im having this same issue im in phpstorm on mac osx
