### ISSUE TITLE
Cannot generate types from `schema.json`.

### ISSUE THREAD

**Issue by hickscorp** [apollographql/apollo-tooling#966]
This issue might be related to https://github.com/apollographql/apollo-tooling/issues/719, which was closed without much of an explanation.

I have a test query in `src/queries/meQuery.ts`:

```typescript
import { gql } from "apollo-boost";

export default gql`
  query me() {
    user {
      id
      firstName
      lastName
      email
      labels
    }
  }
`;
```

I'm trying to generate types for my GraphQL frontend to use.

I'm running:
```shell
yarn run \
  apollo codegen:generate \
    --localSchemaFile="schema.json" \
    --addTypename \
    --tagName=gql \
    --target=typescript \
    --includes="src/**/*.ts" \
    --globalTypesFile="src/types/api-types.ts" \
    types
```

The task fails with:

```
yarn run v1.13.0
$ /home/doodloo/Documents/frontend/node_modules/.bin/apollo codegen:generate --localSchemaFile=schema.json --addTypename --tagName=gql --target=typescript types
  ✔ Loading Apollo Project
  ✖ Generating query files with 'typescript' target
    → No operations or fragments found to generate code for.
(node:11348) UnhandledPromiseRejectionWarning: Error: No operations or fragments found to generate code for.
    at write (/home/doodloo/Documents/frontend/node_modules/apollo/lib/commands/client/codegen.js:58:39)
    at GraphQLClientProject.project.onDiagnostics [as _onDiagnostics] (/home/doodloo/Documents/frontend/node_modules/apollo/lib/commands/client/codegen.js:81:29)
    at GraphQLClientProject.validate (/home/doodloo/Documents/frontend/node_modules/apollo-language-server/lib/project/client.js:122:18)
    at GraphQLClientProject.validateIfNeeded (/home/doodloo/Documents/frontend/node_modules/apollo-language-server/lib/project/base.js:131:14)
    at Timeout.setTimeout [as _onTimeout] (/home/doodloo/Documents/frontend/node_modules/apollo-language-server/lib/project/base.js:123:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:11348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:11348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: No operations or fragments found to generate code for.
    at write (~/Documents/frontend/node_modules/apollo/lib/commands/client/codegen.js:58:39)
    at Task.task (~/Documents/frontend/node_modules/apollo/lib/commands/client/codegen.js:83:46)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Apollo version:
```
yarn run apollo --version
yarn run v1.13.0
$ /home/doodloo/Documents/Professional/frontend/node_modules/.bin/apollo --version
apollo/2.4.3 linux-x64 node-v10.15.1
Done in 0.42s.
```

**Comment by chmelevskij** [comment]
Are you sure your `.ts` files have the queries in them? In my case I was getting this error because I was using `gql` only in `.tsx` files. So either doing `--includes="src/**/*"` or `--includes="src/**/*.tsx"` was the solution

**Comment by JakeDawkins** [comment]
Any update on this @hickscorp? Is this still an issue?

**Comment by hickscorp** [comment]
I went through the process of upgrading node and nuking `node_modules` and the problem seems to have went away.

**Comment by JakeDawkins** [comment]
Great! Glad to hear it. Sorry response on this was so late :)
